### ISSUE TITLE
using navigation keys with fcc throws KeyError 'c'

### ISSUE THREAD

**Issue by H4dr1en** [cwerner/fastclass#15]
Using navigation keys (with Left, Up, Down, Right) not in the num pad throws following error:
```
Traceback (most recent call last): 
File "...\envs\py3\lib\tkinter\__init__.py", line 1705, in __call__ return self.func(*args)
File "...\envs\py3\lib\site-packages\fastclass\fc_clean.py", line 133, in callback button_action(event.char)                                                                                                                    File "...\envs\py3\lib\site-packages\fastclass\fc_clean.py", line 129, in button_action self._class[f'c{char}'].add(self.filelist[self._index]) 
KeyError: 'c'
```
The [callback](https://github.com/cwerner/fastclass/blob/master/fastclass/fc_clean.py#L127) function should always use event.keysym to avoid such problems. I fixed it and will open a PR.

**Comment by cwerner** [comment]
Thanks!

Excellent, yes please open a PR.
